Add workflow for cpp

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,3 +52,49 @@ jobs:
             exit 1
             ;;
           esac
+  cpp-pass:
+    uses: ./.github/workflows/cpp.yml
+    with:
+      style-branch: ${{ github.head_ref }}
+      files: ./test/pass.cpp
+  cpp-fail:
+    uses: ./.github/workflows/cpp.yml
+    with:
+      style-branch: ${{ github.head_ref }}
+      continue-on-error: true
+  cpp-fail-clang-format:
+    needs: cpp-fail
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check
+        run: |
+          case ${{ needs.cpp-fail.outputs.passed-clang-format }} in
+          true)
+            echo "::error::Unexpected success"
+            exit 1
+            ;;
+          false)
+            ;;
+          *)
+            echo "::error::Unknown result: ${{ needs.cpp-fail.outputs.passed-clang-format }}"
+            exit 1
+            ;;
+          esac
+  cpp-fail-roslint:
+    needs: cpp-fail
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check
+        run: |
+          case ${{ needs.cpp-fail.outputs.passed-roslint }} in
+          true)
+            echo "::error::Unexpected success"
+            exit 1
+            ;;
+          false)
+            ;;
+          *)
+            echo "::error::Unknown result: ${{ needs.cpp-fail.outputs.passed-roslint }}"
+            exit 1
+            ;;
+          esac
